// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SkyReserves.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241129003734_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyReserves.Models.Accesibilidad", b =>
                {
                    b.Property<int>("AccesibilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccesibilidadId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccesibilidadId");

                    b.ToTable("Accesibilidad");
                });

            modelBuilder.Entity("SkyReserves.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .HasColumnType("int");

                    b.Property<int>("Existencia")
                        .HasColumnType("int");

                    b.Property<string>("Fila")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Letra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("AsientoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            AsientoId = 1,
                            Existencia = 1,
                            Fila = "1",
                            Letra = "A",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 2,
                            Existencia = 1,
                            Fila = "1",
                            Letra = "B",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 3,
                            Existencia = 1,
                            Fila = "2",
                            Letra = "C",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 4,
                            Existencia = 3,
                            Fila = "2",
                            Letra = "D",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 5,
                            Existencia = 1,
                            Fila = "3",
                            Letra = "A",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 6,
                            Existencia = 1,
                            Fila = "3",
                            Letra = "B",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 7,
                            Existencia = 1,
                            Fila = "4",
                            Letra = "C",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 8,
                            Existencia = 3,
                            Fila = "4",
                            Letra = "D",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 9,
                            Existencia = 1,
                            Fila = " 5",
                            Letra = "A",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 10,
                            Existencia = 1,
                            Fila = "5",
                            Letra = "B",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 11,
                            Existencia = 1,
                            Fila = "6",
                            Letra = "C",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 12,
                            Existencia = 3,
                            Fila = "6",
                            Letra = "D",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 13,
                            Existencia = 1,
                            Fila = "7",
                            Letra = "A",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 14,
                            Existencia = 1,
                            Fila = "7",
                            Letra = "B",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 15,
                            Existencia = 1,
                            Fila = "8",
                            Letra = "C",
                            ReservaId = 0
                        },
                        new
                        {
                            AsientoId = 16,
                            Existencia = 3,
                            Fila = "8",
                            Letra = "D",
                            ReservaId = 0
                        });
                });

            modelBuilder.Entity("SkyReserves.Models.ClaseVuelo", b =>
                {
                    b.Property<int>("ClaseVueloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaseVueloId"));

                    b.Property<string>("descripcionClase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClaseVueloId");

                    b.ToTable("ClaseVuelo");
                });

            modelBuilder.Entity("SkyReserves.Models.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<int>("AccesibilidadId")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.HasIndex("AccesibilidadId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SkyReserves.Models.Destino", b =>
                {
                    b.Property<int>("DestinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestinoId"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestinoId");

                    b.ToTable("Destino");
                });

            modelBuilder.Entity("SkyReserves.Models.Hora", b =>
                {
                    b.Property<int>("HoraID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoraID"));

                    b.Property<double>("horaViaje")
                        .HasColumnType("float");

                    b.HasKey("HoraID");

                    b.ToTable("Hora");
                });

            modelBuilder.Entity("SkyReserves.Models.Nacionalidad", b =>
                {
                    b.Property<int>("NacionalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NacionalidadId"));

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NacionalidadId");

                    b.ToTable("Nacionalidad");
                });

            modelBuilder.Entity("SkyReserves.Models.Origen", b =>
                {
                    b.Property<int>("OrigenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrigenId"));

                    b.Property<string>("origen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrigenId");

                    b.ToTable("Origen");
                });

            modelBuilder.Entity("SkyReserves.Models.Pago", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PagoId"));

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.HasKey("PagoId");

                    b.ToTable("Pago");
                });

            modelBuilder.Entity("SkyReserves.Models.Pasaporte", b =>
                {
                    b.Property<int>("PasaporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PasaporteId"));

                    b.Property<string>("CiudadNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmitidoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroPasaporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisResidencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PasaporteId");

                    b.ToTable("Pasaportes");
                });

            modelBuilder.Entity("SkyReserves.Models.PasaporteDetalle", b =>
                {
                    b.Property<int>("PasaporteId")
                        .HasColumnType("int");

                    b.HasKey("PasaporteId");

                    b.ToTable("PasaporteDetalles");
                });

            modelBuilder.Entity("SkyReserves.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"));

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPasajeros")
                        .HasColumnType("int");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("SkyReserves.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Will04",
                            Role = "Admin",
                            UserName = "Wilmer"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Perez05",
                            Role = "User",
                            UserName = "Juan"
                        });
                });

            modelBuilder.Entity("SkyReserves.Models.VuelosEspeciales", b =>
                {
                    b.Property<int>("VuelosEspecialesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VuelosEspecialesId"));

                    b.Property<int>("DestinoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIda")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrigenId")
                        .HasColumnType("int");

                    b.HasKey("VuelosEspecialesId");

                    b.HasIndex("DestinoId");

                    b.HasIndex("OrigenId");

                    b.ToTable("VuelosEspeciales");
                });

            modelBuilder.Entity("SkyReserves.Models.Asiento", b =>
                {
                    b.HasOne("SkyReserves.Models.Reserva", null)
                        .WithMany("AsientoDetalle")
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyReserves.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("SkyReserves.Models.Cliente", b =>
                {
                    b.HasOne("SkyReserves.Models.Accesibilidad", "Accesibilidad")
                        .WithMany()
                        .HasForeignKey("AccesibilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accesibilidad");
                });

            modelBuilder.Entity("SkyReserves.Models.PasaporteDetalle", b =>
                {
                    b.HasOne("SkyReserves.Models.Pasaporte", "Pasaporte")
                        .WithMany("PasaporteDetalle")
                        .HasForeignKey("PasaporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pasaporte");
                });

            modelBuilder.Entity("SkyReserves.Models.Reserva", b =>
                {
                    b.HasOne("SkyReserves.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyReserves.Models.Origen", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("SkyReserves.Models.VuelosEspeciales", b =>
                {
                    b.HasOne("SkyReserves.Models.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkyReserves.Models.Origen", "Origen")
                        .WithMany()
                        .HasForeignKey("OrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destino");

                    b.Navigation("Origen");
                });

            modelBuilder.Entity("SkyReserves.Models.Pasaporte", b =>
                {
                    b.Navigation("PasaporteDetalle");
                });

            modelBuilder.Entity("SkyReserves.Models.Reserva", b =>
                {
                    b.Navigation("AsientoDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
